// frontend/src/components/AddTodo.tsx
import { FormEvent } from "react";
import { addTodo } from "../data/fetchApi";
import { useNavigate } from "react-router-dom";

export function AddTodo()
{
    const navigate = useNavigate();

    const submitTodo = async (event: FormEvent) =>
    {        
        event.preventDefault();
        
        const target = event.target as typeof event.target & {
            title: { value: string };
            description: { value: string };
        };

        const title = target.title.value;
        const description = target.description?.value || ''; 

        const statusCode = await addTodo(title, description);

        if (statusCode === 201)
        {
            navigate('/');
        }
    }

    return (
        <>
            <h2 className="m-2">Add a todo</h2>
            <form role="form" className="m-2" onSubmit={submitTodo}>
                <div className="mb-3">
                    <label htmlFor="title-input" className="form-label">Title</label>
                    <input role="input" type="text" className="form-control" name="title" id="title-input" placeholder="my todo title" required />
                </div>
                <div className="mb-3">
                    <label htmlFor="description-input" className="form-label">add a description if you want</label>
                    <textarea role="textarea" className="form-control" id="description-input" name="description" rows={3}></textarea>
                </div>
                <div className="col-12">
                    <button role="submit" className="btn btn-primary" type="submit">Submit todo</button>
                </div>
            </form>
        </>
    )
}

// angularTodo/src/app/add-todo/add-todo.component.ts
import { Component } from '@angular/core';
import { TodoDataService } from '../todo-data.service';
import { FormBuilder } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  providers: [TodoDataService]
})
export class AddTodoComponent
{
  public todoForm = this.formBuilder.group({
    title: '',
    description: ''
  });

  constructor(
    private todoDataService: TodoDataService,
    private formBuilder: FormBuilder,
    private router: Router
  ) { }

  onSubmit()
  {    
    const { title, description } = this.todoForm.value;

    if (title && typeof title === 'string')
    {
      this.todoDataService.addTodo(title, description ?? '').subscribe((res) =>
      {
        if (res.status === 201)
        {
          this.router.navigate(['list-todo']);
        }
      });
    }
  }
}

<h2 class="m-2">Add a todo</h2>

<form role="form" class="m-2" *ngIf="todoForm" [formGroup]="todoForm" (ngSubmit)="onSubmit()">
    <div class="mb-3">
        <label htmlFor="title-input" class="form-label">Title</label>
        <input role="input" type="text" class="form-control" formControlName="title" id="title-input"
            placeholder="my todo title" required />
    </div>
    <div class="mb-3">
        <label htmlFor="description-input" class="form-label">add a description if you want</label>
        <textarea role="textarea" class="form-control" id="description-input" formControlName="description"
            rows={3}></textarea>
    </div>
    <div class="col-12">
        <button role="submit" class="btn btn-primary" type="submit">Submit todo</button>
    </div>
</form>
